version: "3.5"

services:
  server:
    image: golang:1.19.6-alpine3.16
    # build:
      # context: ./docker/golang
      # dockerfile: Dockerfile
    volumes:
      - .:/server
    working_dir: /server
    ports:
      - "5000:5000"
    depends_on:
      - db
    entrypoint: go run ./go-server/cmd/main.go
    restart: always
  db:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
      # - POSTGRES_USER={DB_USER}
      # - POSTGRES_PASSWORD={DB_PASSWORD}
      # - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./go-server/initdb.sh:/docker-entrypoint-initdb/init.sh